# Generated by Django 4.0.3 on 2022-04-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='notes',
            field=models.TextField(max_length=300),
        ),
    ]
